### ISSUE TITLE
Bug when running edges tutorial

### ISSUE THREAD

**Issue by lukemarsden** [pachyderm/aml#33] opened 2021-07-06 10:12 UTC
Run through: https://github.com/pachyderm/aml#advanced-using-pachctl-locally

Then do:

```
pachctl create pipeline -f https://raw.githubusercontent.com/pachyderm/pachyderm/1.13.x/examples/opencv/edges.json
```

Run like:
```
$ cat foo.py
# azureml-core of version 1.0.72 or higher is required
from azureml.core import Workspace, Dataset

subscription_id = '04701c5f-d635-4103-a3a9-0d74aa3ddc51'
resource_group = 'luke-testing'
workspace_name = 'extant'

workspace = Workspace(subscription_id, resource_group, workspace_name)

dataset = Dataset.get_by_name(workspace, name='Pachyderm repo edges')
dataset.download(target_path='.', overwrite=False)
```

Add pdb to `/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/dataprep/api/_rslex_executor.py`:

```
 35                 import pdb; pdb.set_trace()
 36  ->             (batches, num_partitions, stream_columns) = ex.execute(
```

```
Exception: Failed with execution error: error in streaming from input data sources
        ExecutionError(StreamError(Unknown("Could not deserialize result \n custom: missing field `Name`", None)))
=> error in streaming from input data sources
        StreamError(Unknown("Could not deserialize result \n custom: missing field `Name`", None))
=> unexpected error
        Unknown("Could not deserialize result \n custom: missing field `Name`", None)
```

**Comment by lukemarsden** [comment] 2021-07-06 14:19
I wonder if this relates to https://github.com/pachyderm/aml/issues/35 - the blob_dto code talks about `Name` fields - could we end up in that codepath somehow?

**Comment by albscui** [comment] 2021-07-08 13:47
This is caused by a commit not being closed in Pachyderm, which returns an error from the S3G. The problem is that the Rust S3 library doesn't understand Pachyderm specific errors, so it just returns a general error which gets propagated to rslex. Checkout https://github.com/durch/rust-s3/blob/ae166bad53c25c88b9d3784fb816783142400567/s3/src/bucket.rs#L1213

**Comment by lukemarsden** [comment] 2021-07-08 14:26
See also https://pachyderm.slack.com/archives/CEY70V55G/p1625752329186100

**Comment by albscui** [comment] 2021-08-18 16:53
Fixed with `pachctl deploy --no-expose-docker-socket`

https://github.com/pachyderm/aml/blob/main/scripts/install.sh#L42

**Closed by albscui** 2021-08-18 16:53 UTC
